[package]
name = "rscan"
version = "0.1.0"
authors = ["Oliver Daff <oliverdaff@users.noreply.github.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["macros", "tcp", "net"] }
futures = "0.3"